### ISSUE TITLE
Doesn't print history, though field picker has it as an option

### ISSUE THREAD

**Issue by XSchelin** [MrTarantula/WIPrint#12]
With the field picker for a particular ticket type, I added the field "History". Alas, no history is printed at all.

**Comment by MrTarantula** [comment]
I am working on full conversation history, but my schedule has been really full. Now I finally have some time to get back to it. #13 should be an easy fix, but this will take a few weeks.

**Comment by MrTarantula** [comment]
See #2 for an update on this.

**Comment by stevefuzzy** [comment]
Any update on printing conversation history?

**Comment by MrTarantula** [comment]
Conversation history is live with version 2.2.1. Please test it and let me know if there are any issues I have not addressed.

**Comment by MrTarantula** [comment]
I'm assuming all is well. Please open another issue if there are problems.

**Comment by MrTarantula** [comment]
It's a bug in the sense that Microsoft changed their API, breaking my code. They don't release changelogs or notify of breaking changes, so extension development is always a moving target.
