### ISSUE TITLE
Cannot change fields for Bug type at all

### ISSUE THREAD

**Issue by XSchelin** [MrTarantula/WIPrint#13]
Steps:

- Go to the Work Item Print page.
- Select Bug.
- Select any field and click the right-hand arrow.

The field disappears, but doesn't show in the right-hand column.

The error I see when I load this page:

`VSS.SDK.min.js:3 Error: Syntax error, unrecognized expression: #all-Incident-#`

It appears to be choking on the field we have called "Incident #".

**Comment by XSchelin** [comment]
Ah yes -- in that there are no further fields _after_ "Incident #", whoops.

**Comment by MrTarantula** [comment]
Can you hit this API with your browser and send me the resulting JSON?

`http://{instance}/{collection}/{project}/_apis/wit/workItemTypes/{name}`

I really only need the `fieldInstances` array, if you don't feel comfortable sharing a lot of data.

**Comment by XSchelin** [comment]
[fieldInstances.txt](https://github.com/MrTarantula/WIPrint/files/1349214/fieldInstances.txt)

**Comment by MrTarantula** [comment]
Perfect. I removed the link on the file just in case. Can't be too careful. I'll let you know once the bug is fixed.

**Comment by MrTarantula** [comment]
Extension has been updated to v2.0.2. For VSTS it should update automatically.

**Comment by XSchelin** [comment]
Nice, it totally works now. Thank you for the quick turnaround!

**Comment by MrTarantula** [comment]
No problem. It wasn't difficult to fix, but since it's a complete showstopper I think it warranted a quick solution. I would have gotten to it sooner but I was camping all weekend.

**Comment by XSchelin** [comment]
How very dare you have a life outside of coding, you monster. ;)
