### ISSUE TITLE
Print button on Backlog Items/Task do not react

### ISSUE THREAD

**Issue by KurtSF** [MrTarantula/WIPrint#15]
See attached. Using this button result in nothing - when opening the Backlog Item and use print from there works fine.
![printerrorvsts](https://user-images.githubusercontent.com/32479587/31116599-fa3da1e6-a826-11e7-8d6d-2607b34babbd.JPG)

**Comment by MrTarantula** [comment]
v2.0.3 was just released, which fixes printing from the board. Please verify that it works.

**Comment by KurtSF** [comment]
It seems to work fine!
Thank you for a fast response!


Best Regards/Med venlig hilsen
Kurt S. Frederichsen
ScrumMaster

Danfoss A/S
Danfoss Cooling Systems
R&D Methodology
L21-N12
Nordborgvej 81
6430 Nordborg

Mobile: +45 2557 9305
E-mail: ksf@danfoss.com<mailto:ksf@danfoss.com>
www.danfoss.com<http://www.danfoss.com/>

**Comment by MrTarantula** [comment]
Good. I fixed the other bugs you mentioned in your marketplace rating as well. I would greatly appreciate it if you could revise your rating. Thank you.
