### ISSUE TITLE
Does WIPrint work for chrome/safari/mac ?

### ISSUE THREAD

**Issue by vfalcao** [MrTarantula/WIPrint#16]
Thanks for the quick response.
Actually, I've found out that if I access my company tfs server via https, the plugins don't work.
It seems that mixed content ( http x https ) is somewhat buggy, or the initial setup was not done
correctly. 
I was able to use your plugin successfully, accessing my tfs server via http.
By the way, congratulations for your plugin, it's very useful.

**Comment by MrTarantula** [comment]
There's no reason why it shouldn't work in Chrome or Safari on Mac, but I don't have a Mac so I can't test it. If it does not work, I would be more than happy to fix it.

**Comment by vfalcao** [comment]
Thanks for the quick response.
Actually, I've found out that if I access my company tfs server via https, the plugins don't work.
It seems that mixed content ( http x https ) is somewhat buggy, or the initial setup was not done
correctly.
I was able to use your plugin successfully, accessing my tfs server via http.
By the way, congratulations for your plugin, it's very useful.

**Comment by MrTarantula** [comment]
I haven't tried it over https on TFS, but VSTS is secure so it should work similarly. There's definitely no hardcoded URLs in my extension.

Thanks for the feedback!
