### ISSUE TITLE
Does not print conversation history (discussion)

### ISSUE THREAD

**Issue by wesmacdonald** [MrTarantula/WIPrint#2]
Hi,

The extension does not inlcude the entire discussion field.

Regards,
Wes

**Comment by MrTarantula** [comment]
I plan on adding full conversation history soon. The fields of the work item object only contain the latest entry, so it was trivial to include it. Looking at the API, there's `getUpdates()`, `getHistory()`, `getRevisions()`, and a completely undocumented method `getComments()`. Once I have time to sit down and figure out which is best I will get it included.

**Comment by MrTarantula** [comment]
I have completely reworked a lot of the extension and once I have released it I will look into printing the complete history.

**Comment by stevefuzzy** [comment]
I would like to add a request for ability to print complete Discussion as well.

**Comment by peckhamm** [comment]
Since you haven't had a chance to wrap this up yet, I'm hoping that you can find a way to include in that history, who and when the parts in the conversation took place.  Thank you in advance.

**Comment by MrTarantula** [comment]
I have history basically working in a test build. I'm playing with the formatting, but right now there is a top header for History, and all of the individual items are indented slightly. Each comment has a header with time, date, and username, then the text begins on the next line. I'm pretty happy that it keeps most of the formatting. Suggestions on formatting/placement?

![image](https://user-images.githubusercontent.com/11617455/31318478-09113188-ac19-11e7-9a58-43d0d8077734.png)

**Comment by peckhamm** [comment]
The only change I would make to what's above is an extra space above the date line of a new entry.  Other than that, it's exactly what I am looking for.

**Comment by MrTarantula** [comment]
Yes, I noticed that after I posted the image. I'll add a bit of padding. The only thing left for me to do is make it work reliably in TFS 2015 and 2017/VSTS, and I'll update the extension.

**Comment by stevefuzzy** [comment]
Hi.  Any idea when you will update the extension to support printing of conversation history?

**Comment by MrTarantula** [comment]
I was nearly done with it, and then I tried to add a couple of other features. This snowballed into rewriting a lot of it. Then I put the whole thing on hold.

I will get conversation history merged in very soon, then do all the other stuff later.

**Comment by MrTarantula** [comment]
Conversation history is live with version 2.2.1. Please test it and let me know if there are any issues I have not addressed.

**Comment by MrTarantula** [comment]
I'm assuming all is well. Please open another issue if there are problems.
