### ISSUE TITLE
Hotkey to print? Ctrl+P print screen

### ISSUE THREAD

**Issue by ryanjones** [MrTarantula/WIPrint#24]
First off - fantastic addon. Thanks for the hard work. 

Quick question. Have you given any thoughts to having a hot key that triggers a print within a work item? If I hit Ctrl + P now I get the following:

![image](https://user-images.githubusercontent.com/350391/43474045-ff492e4c-94ae-11e8-88f7-af941c536760.png)

I think this is something I can try and contribute back if you're interested in having a hot key to print. Not sure what type of events I can hook into, but I assume there's some type of key down or print event I can tap into.

**Comment by MrTarantula** [comment]
I don't know if any other extensions implement hotkeys, but there are some built into TFS/VSTS. I don't think there are extension points for hotkeys, although that would be nice. 

If you want to add a hotkey, try not to override any [here](https://docs.microsoft.com/en-us/vsts/project/navigation/keyboard-shortcuts?view=vsts). I'm also not sure about overriding `Ctrl+P`. I'd like to see some "prior art" that this is commonly done.

**Comment by ryanjones** [comment]
Thanks for the feedback. I can't seem to find anything for hot keys yet :(. I'll have to dig a bit more, but nothing seems to be exposed that I can tell :(

That being said I've used your plugin as a base for some functionality I was looking for. Thanks again for your hard work :D! I'm building a slimmed down version only focused on user stories/bugs (https://github.com/ryanjones/WIPrint/pull/1)
