### ISSUE TITLE
Azure DevOps Update Icon

### ISSUE THREAD

**Issue by carlowahlstedt** [MrTarantula/WIPrint#26]
With the Azure DevOps UI redesign, an update is needed to add an icon.

<img width="286" alt="screen shot 2018-09-19 at 10 56 54 am" src="https://user-images.githubusercontent.com/2687687/45761702-bf452d00-bbfa-11e8-8c29-83c97751df3d.png">

If you'd like assistance in this please let me know and any suggestion you have of an icon (or I will otherwise make one)

**Comment by MrTarantula** [comment]
I'll just use the icon I'm using for the menu item. Thanks for the heads up!

**Comment by MrTarantula** [comment]
I have added the icon:

![image](https://user-images.githubusercontent.com/11617455/48293127-32bd2b00-e443-11e8-8b90-cff02bee3217.png)

Thanks for bringing this to my attention.

**Comment by carlowahlstedt** [comment]
Looks great and verified it's working!

**Comment by MrTarantula** [comment]
You mentioned you could make icons. I have a library called [NDice](https://github.com/MrTarantula/NDice) that I've been wanting to make a banner for the readme, and an icon for Nuget, but I'm a terrible artist. I totally understand if you don't want to work for free for a completely unknown lib. But on the off chance that you have some free time, here's what I would like:

* A simple six-sided die, maybe balancing on its edge, or some other clue to show that there's something not right about it.
* Simple lines, no gradients or shadows. Two or three colors at most. Just black and white is fine.
* 256x256 icon.
* Banner with icon on the left and the name of the library (NDice) next to it. Not too big, max height of 100 or so, and wide enough to look decent on Github.

Again, feel no obligation to do this. It's just a pet project of mine and I want it to look nice, on the off chance someone actually uses it.

**Comment by carlowahlstedt** [comment]
So I can only really do simple stuff or take something free and make alterations to it. I'm not amazing by any chance.

In this instance, if I was going to do it for myself I would start by looking at free icons like [iconfinder](https://www.iconfinder.com/search/?q=dice&price=free), [noun project](https://thenounproject.com/search/?q=dice), [flat icon](https://www.flaticon.com/search?word=dice), [icons8](https://icons8.com/icon/set/dice/all). If I found something I liked, I would take it and try to make alterations to it. Change colors, clean it up, move it around, etc. 

I'm comfortable doing all this because I'm not trying to sell something but just make it look good. If you around at those and have a thought for what you'd like to do to match what you mention above, I wouldn't mind to try to produce SOMETHING for you. I just can't promise anything amazing.

If you find something, then just open an issue on that library and tag me. I'll grab it and take a look when I get a chance.

**Comment by carlowahlstedt** [comment]
Oh, sometimes I'll also grab an image from a place like [pexels](https://www.pexels.com/photo/red-translucent-die-on-top-of-black-surface-979722/), crop or alter it to my linking.

**Comment by MrTarantula** [comment]
That sounds like about what I would do, but I wasn't aware of the resources you mentioned. I can probably figure out something from there. If I need any help I might ping you though.

Thanks for the information!
