### ISSUE TITLE
Can you change the license?

### ISSUE THREAD

**Issue by WouterDeKort** [MrTarantula/WIPrint#27]
My organization would like to use this but the extension has a copy left license. Are you willing to change the license to a more open license model?

Thanks,
Wouter

**Comment by MrTarantula** [comment]
I can change it to MIT. It will be a little while before I can update the actual extension. Is changing it in the repo enough?

**Comment by nschonni** [comment]
> My organization would like to use this but the extension has a copy left license.

Doesn't really matter now that it has changed, but I don't see why the license would matter if you are just using the extension. Maybe if it was a build extension that was actually used in the build process, the copyleft part might affect you.

**Comment by MrTarantula** [comment]
As of v2.3.0, the license is MIT.

**Comment by WouterDeKort** [comment]
Thanks!
