### ISSUE TITLE
Incorrect fields when printing bugs

### ISSUE THREAD

**Issue by davecwilliams** [MrTarantula/WIPrint#4]
When printing a bug it attempts to print Description and Acceptance Criteria, with the text "No Description" and "No Acceptance Criteria" which makes sense because those fields do not exist for bugs.

We would like to see Repro Steps and System Info fields displayed in the print job, as well as Planning, Priority and Effort.

I believe there is another ticket stating that only the last discussion item is printed, and not the whole discussion.

**Comment by MrTarantula** [comment]
Customization is coming soon. Would it be beneficial to have different templates for all work item types? E.g. a template for bugs, a template for work items, a template for projects, or is that too much customization?

**Comment by davecwilliams** [comment]
In my opinion I think different templates may be required, or at least the ability for users to select what components they would like displayed.

**Comment by MrTarantula** [comment]
Thanks for the feedback. I will let you know here when the new version is ready.

**Comment by MrTarantula** [comment]
I am in the process of adding more customization and would like some feedback. You an download a test extension [here](https://github.com/MrTarantula/WIPrint/releases/download/v1.1.1-test/mrtarantula.wiprint-dev-1.1.1.vsix) to try it out. To customize fields you will need to go to your project's admin settings. There will be a tab called "Work Item Print" where you can select all the fields you want.

You can install it side-by-side with the other extension, the menu items are prefixed with "DEV".

**Comment by MrTarantula** [comment]
I have a newer build [here](https://github.com/MrTarantula/WIPrint/releases/download/v1.1.3-test/mrtarantula.wiprint-dev-1.1.3.vsix). Just some bug fixes and better UI. I'll start working on per-type customization soon.

**Comment by MrTarantula** [comment]
I have a new test build that offers per item customization, a better UI, and the configuration shows as a Work hub. You can download it [here](https://github.com/MrTarantula/WIPrint/releases/download/v1.2.0/mrtarantula.wiprint-dev-1.2.0.vsix).

I'm doing a little more testing but should officially release it soon.

**Comment by MrTarantula** [comment]
I have released a new version of the extension. which includes per-item customization. You can find it in the [marketplace](https://marketplace.visualstudio.com/items?itemName=mrtarantula.wiprint).

If you like the extension, please rate or review it there. Thanks.

**Comment by davecwilliams** [comment]
It appears to be showing even less than before. 
![bugdescription](https://user-images.githubusercontent.com/29951796/29276096-7b10c0b4-80db-11e7-8e4a-ab120802a027.png)
![bugprint](https://user-images.githubusercontent.com/29951796/29276097-7b118db4-80db-11e7-8bce-27d9df119ee8.png)

**Comment by MrTarantula** [comment]
There is a default configuration of the same fields that were in the initial release, which were
```
"System.ID",
"System.Title",
"System.AssignedTo",
"System.Description",
"System.State",
"System.History",
"System.WorkItemType",
"System.CreatedDate",
"Microsoft.VSTS.Scheduling.DueDate",
"Microsoft.VSTS.Scheduling.StartDate",
"Microsoft.VSTS.Common.AcceptanceCriteria"
```

Also, if any of those are blank, null, or undefined they won't be rendered. There is now a "Work Item Print" hub under the **Work** section where you can configure the fields that will print for each work item type. So now you can choose which fields will be displayed for bugs separate from user stories, tasks, projects, etc...

**Comment by MrTarantula** [comment]
See #2 for updates on conversation history. I believe the other issues have been addressed in recent updates. If you're happy with everything except history, please close the issue.

**Comment by MrTarantula** [comment]
Conversation history is live with version 2.2.1. Please test it and let me know if there are any issues I have not addressed.

**Comment by MrTarantula** [comment]
I'm assuming all is well. Please open another issue if there are problems.
