### ISSUE TITLE
Error - The page you are looking for is currently unavailable in TFS 2017

### ISSUE THREAD

**Issue by japaricio1** [MrTarantula/WIPrint#5]
Using the print button on a work item (user story) or using the right-click print option, print the attached error.

![image](https://user-images.githubusercontent.com/15270324/28394405-bbb9cbe0-6ca1-11e7-8e93-eed55152b589.png)

**Comment by japaricio1** [comment]
Using IE 11

**Comment by MrTarantula** [comment]
All other browsers work except IE11. Still trying to figure that out. I will let you know once it's working.

**Comment by MrTarantula** [comment]
Can you try [this](https://github.com/MrTarantula/WIPrint/releases/download/v1.1.3-test/mrtarantula.wiprint-dev-1.1.3.vsix) test build? It will run alongside the original extension. All of the menu items are prefixed with "DEV". Also, you will need to configure the fields you want to print by going to your project settings (gear icon at the top) and going to the "Work Item Print" tab.

**Comment by MrTarantula** [comment]
I have released a new version of the extension. New features have been added, and your bug has been addressed. You can find it in the [marketplace](https://marketplace.visualstudio.com/items?itemName=mrtarantula.wiprint).

If you like the extension, please rate or review it there. Thanks.

**Comment by MrTarantula** [comment]
Oops. I'll let you close this if you're satisfied.

**Comment by MrTarantula** [comment]
I'm assuming all is well. Please open another issue if there are problems.
