### ISSUE TITLE
When selecting multiple items from a query, query order is not respected

### ISSUE THREAD

**Issue by jeffyoungstrom** [MrTarantula/WIPrint#8]
If I select a set of items from the results of a query, they are printed in numeric order by ID instead of maintaining the sorted order in the query results.

**Comment by MrTarantula** [comment]
There's not a whole lot I can do about that. TFS would have to preserve that order for me to consume from the query context. VSTS does (I just checked) but it looks like 2015 always orders by ID.

**Comment by jeffyoungstrom** [comment]
Fair enough. Hopefully on-prem 2017 works too as I plan to upgrade to that soon.

**Comment by MrTarantula** [comment]
I think it will work. At least it appears to. The only TFS 2017 instance I have access to right now is my full-time jobs', and I can't install my extension there yet, but the work item ID array is in the correct order when I sort it.

**Comment by MrTarantula** [comment]
I'm closing this as it's not something I can control, and I believe it works in newer TFS versions and VSTS.
